services:
  - type: web
    name: deepseek-summarizer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You will add this manually in the dashboard
